name: "Build Wi (GCC/MSVC/MinGW/EMCC)"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    name: GCC (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build with GCC
        run: |
          xmake f --toolchain=gcc
          xmake

  windows:
    name: MSVC (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build with MSVC
        run: |
          xmake f --toolchain=msvc 
          xmake -j1

  mingw:
    name: MinGW (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build with MinGW
        run: |
          xmake f -p windows --toolchain=mingw
          xmake

  wasm:
    name: EMCC (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build with emcc
        run: |
          xmake f -p wasm
          xmake
