name: "Build Wi (GCC/MSVC)"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build with GCC
        run: |
          xmake f --toolchain=gcc
          xmake

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build with MSVC
        run: |
          xmake f --toolchain=msvc 
          xmake
